#!/usr/bin/env ruby
# frozen_string_literal: true

app_name = ARGV[0]

unless app_name
  puts "Usage: ./bootstrap app-name"
  exit -1
end

snake_name = app_name.tr('_', '-')
underscore_name = app_name.tr('-', '_')
human_name = underscore_name.split('_').map(&:capitalize).join(' ')
camelcased_name = human_name.delete(' ')

def run(cmd)
  puts cmd
  system(cmd) or exit -1
end

def replace(changes)
  puts "Replacing #{changes.map { |from, to| %|"#{from} with "#{to}"| }.join(', ')}"
  Dir["**/*", ".env*", "app.json"].each do |file|
    next if File.directory?(file)

    content = File.read(file)
    new_content = changes.inject(content) do |content, change|
      from, to = change
      content.gsub(from, to)
    end
    if content != new_content
      File.open(file, 'w') do |f|
        f.puts new_content
      end
    end
  end
end

# run %|mv README-TEMPLATE.md README.md|

replace(
  "canvas-rails-template" => snake_name,
  "canvas_rails_template" => underscore_name,
  "Canvas Rails Template" => human_name,
  "CanvasRailsTemplate"   => camelcased_name,
)

run %|rm bootstrap| # self destruct!
run %|git add --all . && git commit -m "Bootstrap #{human_name}"|

puts "#{human_name} is ready! Happy coding!"
